package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ALL_SPECIES".
 */
public class AllSpecies {

    private String id;
    private String title;
    private String description;
    private String speciesType;
    private String sizeLimit;
    private String bagLimit;
    private Boolean grouped;
    private String image;
    private String thumbnailImage;
    private byte[] byteThumbnailFresh;
    private byte[] byteImageFresh;
    private String subHeader;
    private String ruleBagLimit;
    private String groupType;

    // KEEP FIELDS - put your custom fields here

    public AllSpeciesGroup fishGroup;
    public AllSpeciesfishFacts fishFacts;
    public AllSpeciesrules rules;
    // KEEP FIELDS END

    public AllSpecies() {
    }

    public AllSpecies(String id, String title, String description, String speciesType, String sizeLimit, String bagLimit, Boolean grouped, String image, String thumbnailImage, byte[] byteThumbnailFresh, byte[] byteImageFresh, String subHeader, String ruleBagLimit, String groupType) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.speciesType = speciesType;
        this.sizeLimit = sizeLimit;
        this.bagLimit = bagLimit;
        this.grouped = grouped;
        this.image = image;
        this.thumbnailImage = thumbnailImage;
        this.byteThumbnailFresh = byteThumbnailFresh;
        this.byteImageFresh = byteImageFresh;
        this.subHeader = subHeader;
        this.ruleBagLimit = ruleBagLimit;
        this.groupType = groupType;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSpeciesType() {
        return speciesType;
    }

    public void setSpeciesType(String speciesType) {
        this.speciesType = speciesType;
    }

    public String getSizeLimit() {
        return sizeLimit;
    }

    public void setSizeLimit(String sizeLimit) {
        this.sizeLimit = sizeLimit;
    }

    public String getBagLimit() {
        return bagLimit;
    }

    public void setBagLimit(String bagLimit) {
        this.bagLimit = bagLimit;
    }

    public Boolean getGrouped() {
        return grouped;
    }

    public void setGrouped(Boolean grouped) {
        this.grouped = grouped;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getThumbnailImage() {
        return thumbnailImage;
    }

    public void setThumbnailImage(String thumbnailImage) {
        this.thumbnailImage = thumbnailImage;
    }

    public byte[] getByteThumbnailFresh() {
        return byteThumbnailFresh;
    }

    public void setByteThumbnailFresh(byte[] byteThumbnailFresh) {
        this.byteThumbnailFresh = byteThumbnailFresh;
    }

    public byte[] getByteImageFresh() {
        return byteImageFresh;
    }

    public void setByteImageFresh(byte[] byteImageFresh) {
        this.byteImageFresh = byteImageFresh;
    }

    public String getSubHeader() {
        return subHeader;
    }

    public void setSubHeader(String subHeader) {
        this.subHeader = subHeader;
    }

    public String getRuleBagLimit() {
        return ruleBagLimit;
    }

    public void setRuleBagLimit(String ruleBagLimit) {
        this.ruleBagLimit = ruleBagLimit;
    }

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
