package com.mobiddiction.fishsmart.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.mobiddiction.fishsmart.dao.AllSpeciesfishFacts;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALL_SPECIESFISH_FACTS".
*/
public class AllSpeciesfishFactsDao extends AbstractDao<AllSpeciesfishFacts, Void> {

    public static final String TABLENAME = "ALL_SPECIESFISH_FACTS";

    /**
     * Properties of entity AllSpeciesfishFacts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "id", false, "ID");
        public final static Property About = new Property(1, String.class, "about", false, "ABOUT");
        public final static Property FreshID = new Property(2, String.class, "FreshID", false, "FRESH_ID");
        public final static Property Size = new Property(3, String.class, "size", false, "SIZE");
        public final static Property ConfusingSpecies = new Property(4, String.class, "confusingSpecies", false, "CONFUSING_SPECIES");
        public final static Property Characteristics = new Property(5, String.class, "characteristics", false, "CHARACTERISTICS");
    }


    public AllSpeciesfishFactsDao(DaoConfig config) {
        super(config);
    }
    
    public AllSpeciesfishFactsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALL_SPECIESFISH_FACTS\" (" + //
                "\"ID\" INTEGER," + // 0: id
                "\"ABOUT\" TEXT," + // 1: about
                "\"FRESH_ID\" TEXT," + // 2: FreshID
                "\"SIZE\" TEXT," + // 3: size
                "\"CONFUSING_SPECIES\" TEXT," + // 4: confusingSpecies
                "\"CHARACTERISTICS\" TEXT);"); // 5: characteristics
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALL_SPECIESFISH_FACTS\"";
        db.execSQL(sql);
    }

    @Override
    protected void bindValues(DatabaseStatement stmt, AllSpeciesfishFacts entity) {
        stmt.clearBindings();

        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String about = entity.getAbout();
        if (about != null) {
            stmt.bindString(2, about);
        }

        String FreshID = entity.getFreshID();
        if (FreshID != null) {
            stmt.bindString(3, FreshID);
        }

        String size = entity.getSize();
        if (size != null) {
            stmt.bindString(4, size);
        }

        String confusingSpecies = entity.getConfusingSpecies();
        if (confusingSpecies != null) {
            stmt.bindString(5, confusingSpecies);
        }

        String characteristics = entity.getCharacteristics();
        if (characteristics != null) {
            stmt.bindString(6, characteristics);
        }
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AllSpeciesfishFacts entity) {
        stmt.clearBindings();
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String about = entity.getAbout();
        if (about != null) {
            stmt.bindString(2, about);
        }
 
        String FreshID = entity.getFreshID();
        if (FreshID != null) {
            stmt.bindString(3, FreshID);
        }
 
        String size = entity.getSize();
        if (size != null) {
            stmt.bindString(4, size);
        }
 
        String confusingSpecies = entity.getConfusingSpecies();
        if (confusingSpecies != null) {
            stmt.bindString(5, confusingSpecies);
        }
 
        String characteristics = entity.getCharacteristics();
        if (characteristics != null) {
            stmt.bindString(6, characteristics);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public AllSpeciesfishFacts readEntity(Cursor cursor, int offset) {
        AllSpeciesfishFacts entity = new AllSpeciesfishFacts( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // about
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // FreshID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // size
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // confusingSpecies
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // characteristics
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AllSpeciesfishFacts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setAbout(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFreshID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSize(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setConfusingSpecies(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCharacteristics(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(AllSpeciesfishFacts entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(AllSpeciesfishFacts entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    @Override
    protected boolean hasKey(AllSpeciesfishFacts entity) {
        return false;
    }
}
