package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FIRST_TIME_LOAD".
 */
public class FirstTimeLoad {

    private Boolean isFirstTimeLoad;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FirstTimeLoad() {
    }

    public FirstTimeLoad(Boolean isFirstTimeLoad) {
        this.isFirstTimeLoad = isFirstTimeLoad;
    }

    public Boolean getIsFirstTimeLoad() {
        return isFirstTimeLoad;
    }

    public void setIsFirstTimeLoad(Boolean isFirstTimeLoad) {
        this.isFirstTimeLoad = isFirstTimeLoad;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
