package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GALLERY_IMAGE".
 */
public class GalleryImage implements java.io.Serializable {

    private String createdBy;
    private String createdDate;
    private String lastModifiedDate;
    private String id;
    private String name;
    private String state;
    private String url;
    private String favourite;
    private String deleted;
    private String clientId;
    private String userId;
    private String newsId;
    private String eventId;
    private String driverId;
    private String galleryId;
    private String jobId;
    private String catchId;
    private String note;
    private String expiry;
    private String profile;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GalleryImage() {
    }

    public GalleryImage(String createdBy, String createdDate, String lastModifiedDate, String id, String name, String state, String url, String favourite, String deleted, String clientId, String userId, String newsId, String eventId, String driverId, String galleryId, String jobId, String catchId, String note, String expiry, String profile) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.id = id;
        this.name = name;
        this.state = state;
        this.url = url;
        this.favourite = favourite;
        this.deleted = deleted;
        this.clientId = clientId;
        this.userId = userId;
        this.newsId = newsId;
        this.eventId = eventId;
        this.driverId = driverId;
        this.galleryId = galleryId;
        this.jobId = jobId;
        this.catchId = catchId;
        this.note = note;
        this.expiry = expiry;
        this.profile = profile;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    public String getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(String lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFavourite() {
        return favourite;
    }

    public void setFavourite(String favourite) {
        this.favourite = favourite;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getDriverId() {
        return driverId;
    }

    public void setDriverId(String driverId) {
        this.driverId = driverId;
    }

    public String getGalleryId() {
        return galleryId;
    }

    public void setGalleryId(String galleryId) {
        this.galleryId = galleryId;
    }

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getCatchId() {
        return catchId;
    }

    public void setCatchId(String catchId) {
        this.catchId = catchId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getExpiry() {
        return expiry;
    }

    public void setExpiry(String expiry) {
        this.expiry = expiry;
    }

    public String getProfile() {
        return profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
