package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOGIN_RESPONSE".
 */
public class LoginResponse {

    private String Authorization;
    private String userId;
    private String changePassword;
    private String termsAccepted;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LoginResponse() {
    }

    public LoginResponse(String Authorization, String userId, String changePassword, String termsAccepted) {
        this.Authorization = Authorization;
        this.userId = userId;
        this.changePassword = changePassword;
        this.termsAccepted = termsAccepted;
    }

    public String getAuthorization() {
        return Authorization;
    }

    public void setAuthorization(String Authorization) {
        this.Authorization = Authorization;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getChangePassword() {
        return changePassword;
    }

    public void setChangePassword(String changePassword) {
        this.changePassword = changePassword;
    }

    public String getTermsAccepted() {
        return termsAccepted;
    }

    public void setTermsAccepted(String termsAccepted) {
        this.termsAccepted = termsAccepted;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
