package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEW_LICENCE_DATA".
 */
public class NewLicenceData {

    private String contactAndLicensingType;
    private String title;
    private String description;
    private String url;
    private String phone;
    private String mobile;
    private String subType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewLicenceData() {
    }

    public NewLicenceData(String contactAndLicensingType, String title, String description, String url, String phone, String mobile, String subType) {
        this.contactAndLicensingType = contactAndLicensingType;
        this.title = title;
        this.description = description;
        this.url = url;
        this.phone = phone;
        this.mobile = mobile;
        this.subType = subType;
    }

    public String getContactAndLicensingType() {
        return contactAndLicensingType;
    }

    public void setContactAndLicensingType(String contactAndLicensingType) {
        this.contactAndLicensingType = contactAndLicensingType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getSubType() {
        return subType;
    }

    public void setSubType(String subType) {
        this.subType = subType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
