package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEW_MAP_DATA".
 */
public class NewMapData {

    private String id;
    private String Title;
    private String description;
    private String color;
    private String mapType;
    private Double zoom;
    private Double topLeftLat;
    private Double topLeftLon;
    private Double bottomRightLat;
    private Double bottomRightLon;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewMapData() {
    }

    public NewMapData(String id, String Title, String description, String color, String mapType, Double zoom, Double topLeftLat, Double topLeftLon, Double bottomRightLat, Double bottomRightLon) {
        this.id = id;
        this.Title = Title;
        this.description = description;
        this.color = color;
        this.mapType = mapType;
        this.zoom = zoom;
        this.topLeftLat = topLeftLat;
        this.topLeftLon = topLeftLon;
        this.bottomRightLat = bottomRightLat;
        this.bottomRightLon = bottomRightLon;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getMapType() {
        return mapType;
    }

    public void setMapType(String mapType) {
        this.mapType = mapType;
    }

    public Double getZoom() {
        return zoom;
    }

    public void setZoom(Double zoom) {
        this.zoom = zoom;
    }

    public Double getTopLeftLat() {
        return topLeftLat;
    }

    public void setTopLeftLat(Double topLeftLat) {
        this.topLeftLat = topLeftLat;
    }

    public Double getTopLeftLon() {
        return topLeftLon;
    }

    public void setTopLeftLon(Double topLeftLon) {
        this.topLeftLon = topLeftLon;
    }

    public Double getBottomRightLat() {
        return bottomRightLat;
    }

    public void setBottomRightLat(Double bottomRightLat) {
        this.bottomRightLat = bottomRightLat;
    }

    public Double getBottomRightLon() {
        return bottomRightLon;
    }

    public void setBottomRightLon(Double bottomRightLon) {
        this.bottomRightLon = bottomRightLon;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
