package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEW_MAP_PINS_LAT_LON_DATA".
 */
public class NewMapPinsLatLonData {

    private String id;
    private Double lat;
    private Integer zoom;
    private Double lon;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewMapPinsLatLonData() {
    }

    public NewMapPinsLatLonData(String id, Double lat, Integer zoom, Double lon) {
        this.id = id;
        this.lat = lat;
        this.zoom = zoom;
        this.lon = lon;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Integer getZoom() {
        return zoom;
    }

    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
