package com.mobiddiction.fishsmart.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.mobiddiction.fishsmart.dao.NewRulesGuide;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEW_RULES_GUIDE".
*/
public class NewRulesGuideDao extends AbstractDao<NewRulesGuide, Void> {

    public static final String TABLENAME = "NEW_RULES_GUIDE";

    /**
     * Properties of entity NewRulesGuide.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FishingGuideType = new Property(0, String.class, "fishingGuideType", false, "FISHING_GUIDE_TYPE");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
    }


    public NewRulesGuideDao(DaoConfig config) {
        super(config);
    }
    
    public NewRulesGuideDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_RULES_GUIDE\" (" + //
                "\"FISHING_GUIDE_TYPE\" TEXT," + // 0: fishingGuideType
                "\"ID\" TEXT);"); // 1: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_RULES_GUIDE\"";
        db.execSQL(sql);
    }

    @Override
    protected void bindValues(DatabaseStatement stmt, NewRulesGuide entity) {
        stmt.clearBindings();

        String fishingGuideType = entity.getFishingGuideType();
        if (fishingGuideType != null) {
            stmt.bindString(1, fishingGuideType.replaceAll("\\s+",""));
        }

        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NewRulesGuide entity) {
        stmt.clearBindings();
 
        String fishingGuideType = entity.getFishingGuideType();
        if (fishingGuideType != null) {
            stmt.bindString(1, fishingGuideType.replaceAll("\\s+",""));
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public NewRulesGuide readEntity(Cursor cursor, int offset) {
        NewRulesGuide entity = new NewRulesGuide( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // fishingGuideType
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NewRulesGuide entity, int offset) {
        entity.setFishingGuideType(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(NewRulesGuide entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(NewRulesGuide entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    @Override
    protected boolean hasKey(NewRulesGuide entity) {
        return false;
    }
}
