package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEW_RULES_GUIDE".
 */
public class NewRulesGuide {

    private String fishingGuideType;
    private String id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewRulesGuide() {
    }

    public NewRulesGuide(String fishingGuideType, String id) {
        this.fishingGuideType = fishingGuideType;
        this.id = id;
    }

    public String getFishingGuideType() {
        return fishingGuideType;
    }

    public void setFishingGuideType(String fishingGuideType) {
        this.fishingGuideType = fishingGuideType;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
