package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEWSPECIES_DATA".
 */
public class NEWSpeciesData {


    private String createdBy;
    private String createdDate;
    private String lastModifiedBy;
    private String lastModifiedDate;
    private String id;
    private String name;
    private String content;
    private String type_id;
    private ArrayList locationList;
    private ArrayList beaconList;
    private ArrayList userList;
    private ArrayList clientList;
    private Boolean featured;
    private Boolean active;

    // KEEP FIELDS - put your custom fields here

//    public List<SpeciesDataObject> data;
    // KEEP FIELDS END

    public NEWSpeciesData() {
    }

    public NEWSpeciesData(String id, String createdBy, String createdDate, String lastModifiedBy, String lastModifiedDate, String name, String type_id, String content, Boolean featured) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.name = name;
        this.type_id = type_id;
        this.content = content;
        this.featured = featured;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public String getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(String lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType_id() {
        return type_id;
    }

    public void setType_id(String type_id) {
        this.type_id = type_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public ArrayList getLocationList() {
        return locationList;
    }

    public void setLocationList(ArrayList locationList) {
        this.locationList = locationList;
    }

    public ArrayList getBeaconList() {
        return beaconList;
    }

    public void setBeaconList(ArrayList beaconList) {
        this.beaconList = beaconList;
    }

    public ArrayList getUserList() {
        return userList;
    }

    public void setUserList(ArrayList userList) {
        this.userList = userList;
    }

    public ArrayList getClientList() {
        return clientList;
    }

    public void setClientList(ArrayList clientList) {
        this.clientList = clientList;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
