package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "SALT_DATA".
 */
public class SaltData {

    private Long id;
    private Boolean success;

    // KEEP FIELDS - put your custom fields here
    public List<Salt> data;
    // KEEP FIELDS END

    public SaltData() {
    }

    public SaltData(Long id) {
        this.id = id;
    }

    public SaltData(Long id, Boolean success) {
        this.id = id;
        this.success = success;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getSuccess() {
        return success;
    }

    public void setSuccess(Boolean success) {
        this.success = success;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
