package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SALT_WATERFISH_FACTS".
 */
public class SaltWaterfishFacts {

    private String SaltID;
    private Integer id;
    private String about;
    private String size;
    private String confusingSpecies;
    private String characteristics;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SaltWaterfishFacts() {
    }

    public SaltWaterfishFacts(String SaltID, Integer id, String about, String size, String confusingSpecies, String characteristics) {
        this.SaltID = SaltID;
        this.id = id;
        this.about = about;
        this.size = size;
        this.confusingSpecies = confusingSpecies;
        this.characteristics = characteristics;
    }

    public String getSaltID() {
        return SaltID;
    }

    public void setSaltID(String SaltID) {
        this.SaltID = SaltID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAbout() {
        return about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getConfusingSpecies() {
        return confusingSpecies;
    }

    public void setConfusingSpecies(String confusingSpecies) {
        this.confusingSpecies = confusingSpecies;
    }

    public String getCharacteristics() {
        return characteristics;
    }

    public void setCharacteristics(String characteristics) {
        this.characteristics = characteristics;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
