package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SALT_WATERRULES".
 */
public class SaltWaterrules {

    private String SaltID;
    private Integer id;
    private String legalSize;
    private String bagLimit;
    private String possession;
    private String ruleBagLimit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SaltWaterrules() {
    }

    public SaltWaterrules(String SaltID, Integer id, String legalSize, String bagLimit, String possession, String ruleBagLimit) {
        this.SaltID = SaltID;
        this.id = id;
        this.legalSize = legalSize;
        this.bagLimit = bagLimit;
        this.possession = possession;
        this.ruleBagLimit = ruleBagLimit;
    }

    public String getSaltID() {
        return SaltID;
    }

    public void setSaltID(String SaltID) {
        this.SaltID = SaltID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLegalSize() {
        return legalSize;
    }

    public void setLegalSize(String legalSize) {
        this.legalSize = legalSize;
    }

    public String getBagLimit() {
        return bagLimit;
    }

    public void setBagLimit(String bagLimit) {
        this.bagLimit = bagLimit;
    }

    public String getPossession() {
        return possession;
    }

    public void setPossession(String possession) {
        this.possession = possession;
    }

    public String getRuleBagLimit() {
        return ruleBagLimit;
    }

    public void setRuleBagLimit(String ruleBagLimit) {
        this.ruleBagLimit = ruleBagLimit;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
