package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SIGN_UP".
 */
public class SignUp {

    private String id;
    private String firstName;
    private String lastName;
    private String password;
    private String matchingPassword;
    private String email;
    private String mobile;
    private Boolean isUsing2FA;
    private Boolean enabled;
    private String description;
    private String clientId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SignUp() {
    }

    public SignUp(String id, String firstName, String lastName, String password, String matchingPassword, String email, String mobile, Boolean isUsing2FA, Boolean enabled, String description, String clientId) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.matchingPassword = matchingPassword;
        this.email = email;
        this.mobile = mobile;
        this.isUsing2FA = isUsing2FA;
        this.enabled = enabled;
        this.description = description;
        this.clientId = clientId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMatchingPassword() {
        return matchingPassword;
    }

    public void setMatchingPassword(String matchingPassword) {
        this.matchingPassword = matchingPassword;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Boolean getIsUsing2FA() {
        return isUsing2FA;
    }

    public void setIsUsing2FA(Boolean isUsing2FA) {
        this.isUsing2FA = isUsing2FA;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
