package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TERM_CONDITION_VERSION".
 */
public class TermConditionVersion {

    private String id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TermConditionVersion() {
    }

    public TermConditionVersion(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
