package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "TERM_AND_CONDITION".
 */
public class TermAndCondition {

    private String text;
    private String html;

    // KEEP FIELDS - put your custom fields here
    public List<Policies> policies;
    // KEEP FIELDS END

    public TermAndCondition() {
    }

    public TermAndCondition(String text, String html) {
        this.text = text;
        this.html = html;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
