package com.mobiddiction.fishsmart.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.List;

/**
 * Entity mapped to table "USER_OBJ".
 */
public class UserObj {

    private String createdBy;
    private String createdDate;
    private String lastModifiedBy;
    private String lastModifiedDate;
    private String id;
    private String firstName;
    private String lastName;
    private String email;
    private String mobile;
    private String password;
    private String enabled;
    private String description;
    private String invitationAccepted;
    private String clientId;
    private String changePassword;
    private String termsAcceptedNew;
    private String imageId;
    private String using2FA;
    private String image;

    // KEEP FIELDS - put your custom fields here
    public List<UserHistory> userHistory;
    public List<NotificationRoles> roles;

    // KEEP FIELDS END

    public UserObj() {
    }

    public UserObj(String createdBy, String createdDate, String lastModifiedBy, String lastModifiedDate, String id, String firstName, String lastName, String email, String mobile, String password, String enabled, String description, String invitationAccepted, String clientId, String changePassword, String termsAcceptedNew, String imageId, String using2FA, String image) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.mobile = mobile;
        this.password = password;
        this.enabled = enabled;
        this.description = description;
        this.invitationAccepted = invitationAccepted;
        this.clientId = clientId;
        this.changePassword = changePassword;
        this.termsAcceptedNew = termsAcceptedNew;
        this.imageId = imageId;
        this.using2FA = using2FA;
        this.image = image;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public String getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(String lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEnabled() {
        return enabled;
    }

    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getInvitationAccepted() {
        return invitationAccepted;
    }

    public void setInvitationAccepted(String invitationAccepted) {
        this.invitationAccepted = invitationAccepted;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getChangePassword() {
        return changePassword;
    }

    public void setChangePassword(String changePassword) {
        this.changePassword = changePassword;
    }

    public String getTermsAcceptedNew() {
        return termsAcceptedNew;
    }

    public void setTermsAcceptedNew(String termsAcceptedNew) {
        this.termsAcceptedNew = termsAcceptedNew;
    }

    public String getImageId() {
        return imageId;
    }

    public void setImageId(String imageId) {
        this.imageId = imageId;
    }

    public String getUsing2FA() {
        return using2FA;
    }

    public void setUsing2FA(String using2FA) {
        this.using2FA = using2FA;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
